import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import  ScrollToHash from "@/components/hooks/AutoScroll";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} dark`}>
      <head>
        <style>{`
    body {
      margin: 0;
      font-family: system-ui, -apple-system, BlinkMacSystemFont;
    }
  `}</style>
      </head>
      <body className={`antialiased`}>
        <ScrollToHash />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
